---
title: "Ensuring that the questions or quantities of interest are well-defined"
---

1. In order to evaluate uncertainty, the questions and/or quantities of interest for the assessment must be well-defined. This applies both to the assessment as a whole and to different parts of the uncertainty analysis, if it is separated into parts. Any ambiguity in the definition of questions or quantities of interest will add extra uncertainty and make the evaluation more difficult. When a question or quantity of interest is not already well-defined for the purpose of scientific assessment, assessors should define it well for the purpose of uncertainty analysis. 
2. A quantity or question of interest is well-defined if, at least in principle, it could be determined in such a way that assessors would be sure to agree on the answer. A practical way to achieve this is by specifying an experiment, study or procedure that could be undertaken, at least in principle, and which would determine the true answer for the question or quantity with certainty [see SO5.1 for more discussion]. For example: 
   a) a well-defined measure for a quantity of interest, and the time, population or location, and conditions (e.g. status quo or with specified management actions) for which the measure will be considered;
   b) for a question of interest, the presence or absence of one or more clearly-defined states, conditions, mechanisms, etc., of interest for the assessment, and the time, population or location, and conditions (e.g. status quo or with specified management actions) for which this will be considered; 
   c) the result of a clearly-defined scientific study, procedure or calculation, which is established (e.g. in legislation or guidance) as being relevant for the assessment. 
3. When drafting the definition of each question or quantity of interest, check each word in turn. Identify words that are ambiguous (e.g. high), or imply a risk management judgement (e.g. negligible, safe). Replace or define them with words that are, as far as possible, unambiguous and free of risk management connotations or, where appropriate, with numbers. 
4. Sometimes the Terms of Reference for an assessment are very open, e.g. requesting a review of the literature on an area of science. In such cases, assessors should seek to ensure the conclusions they produce either refer to well-defined quantities, or contain welldefined statements that can be considered as answers to well-defined questions, in one of the three forms listed above (point 2, options a–c). This is necessary both for transparency and so that assessors can evaluate and express the uncertainty associated with their conclusions.

