---
title: "Principles of Uncertainty Communication"
---

# Expressions of uncertainty

Messages about uncertainty need to be based on information that is provided in EFSA’s scientific assessments. Therefore, this section describes the main types of expressions of uncertainty that are expected to result from uncertainty analyses following EFSA’s Uncertainty Analysis GD.

- **Unqualified conclusion, with no expression of uncertainty**. This occurs in two situations: 
  - When a standardised assessment procedure only takes into account standard uncertainties, its outcome may be reported as an unqualified conclusion, without any expression of uncertainty (see [UA](https://doi.org/10.2903/j.efsa.2018.5123), [SO](https://doi.org/10.2903/j.efsa.2018.5122) for more explanation) 
  - When uncertainty is present in an assessment, but decision-makers or legislation requires an unqualified conclusion (e.g. safe, not safe or 'cannot conclude'), without any expression of uncertainty. In some of these cases, uncertainty expressions may be included elsewhere in the assessment report, e.g. in the detailed results or in an annex
- **Description of a source of uncertainty**. Verbal description of a source or cause of uncertainty. In some areas of EFSA’s work, there are standard terminologies for describing some types of uncertainties, but often descriptions are specific to the assessment in hand (see [SO](https://doi.org/10.2903/j.efsa.2018.5122))
- **Qualitative description of the direction and/or magnitude of uncertainty using words or symbols**. Words or an ordinal scale describing how much a source of uncertainty affects the assessment or its conclusion (e.g. low, medium or high uncertainty; conservative, very conservative or non-conservative; unlikely, likely or very likely; or symbols indicating the direction and magnitude of uncertainty: —, –,-,+, ++, +++) Because the meaning of such expressions is ambiguous, EFSA’s Uncertainty Analysis GD recommends that they should not be used unless they are accompanied by a quantitative definition (see [UA](https://doi.org/10.2903/j.efsa.2018.5123))
- **Inconclusive assessment**. This occurs in two situations:
  - When decision-makers or legislation require an unqualified conclusion but assessors judge there is too much uncertainty to give one and report that they cannot conclude. The basis for this uncertainty expression should be documented in the body of the assessment report or an annex, and may include one or more uncertainty expressions 
  - When it is not required that conclusions must be unqualified, but the assessors are unable to give any quantitative expression of uncertainty or, where they judge that their probability for a conclusion could be anywhere between 0% and 100%. This should be accompanied by a qualitative description of the uncertainties (see description of 'A precise probability' below)
- **A precise probability**. A single number (in EFSA outputs: a percentage between 0% and 100%) quantifying the likelihood of either: 
  - A specified answer to a question (e.g. a ‘yes’ answer to a ‘yes/no’ question) 
  - A specified quantity lying in a specified range of values, or above or below a specified value (e.g. 90% probability that between 10 and 100 infected organisms will enter the EU in 2019; 5% probability that more than 100 infected organisms will enter).

>Note that the term "precise" is used here to refer to how the probability is expressed, as a single number, and does not imply that it is actually known with absolute precision, which is not possible

- **An approximate probability**. Any range of probabilities (e.g. 10–20% probability) providing an approximate quantification of likelihood for either:
  - A specified answer to a question (e.g. a ‘yes’ answer to a ‘yes/no’ question) 
  - A specified quantity lying in a specified range of values, or above or below a specified value (e.g. 1–10% probability that more than 100 infected organisms will enter the EU in 2019)

> The probability ranges used in EFSA’s approximate probability scale (see @tbl-approx-probscale) are examples of approximate probability expressions. Assessors are not restricted to the ranges in the approximate probability scale and should use whatever ranges best reflect their judgement of the uncertainty (see [UA](https://doi.org/10.2903/j.efsa.2018.5123))

- **A probability distribution**. A graph showing probabilities for different values of an uncertain quantity that has a single true value (e.g. the average exposure for a population). The graph can be plotted in various formats, most commonly a probability density function (PDF), cumulative distribution function (CDF) or complementary cumulative distribution function (CCDF) (see [Section 4.1.4.2 in UC](https://doi.org/10.2903/j.efsa.2019.5520))

- **A two-dimensional probability distribution**. In this guidance, the term ‘two-dimensional (or 2D) probability distribution’ refers to a distribution that quantifies the uncertainty of a quantity that is variable, i.e. takes multiple true values (e.g. the exposure of different individuals in a population). This is most often plotted as a CDF or CCDF representing the median estimate of the variability, with confidence or probability intervals quantifying the uncertainty around the CDF or CCDF.






```{r}
#| label: tbl-approx-probscale
#| tbl-cap: "Approximate probability scale"
#| echo: false
#| message: false
#| warning: false

# update rvest
# install.packages("rvest")
# install the latest version
# remotes::install_github("haozhu233/kableExtra")

library(kableExtra)
library(magrittr)
ptbl <- data.frame(
  term=c("Almost certain", "Extremely likely", "Very likely", "Likely", "About as likely as", "Unlikely", "Very unlikely", "Extremely unlikely", "Almost impossible"),
  range=c("99-100%", "95-99%", "90-95%", "66-90%", "33-66%", "10-33%", "5-10%", "1-5%", "0-1%"),
  addopt=c(rep("More likely than not: >50%", 4), rep(" ", 5)),
  addopt2=rep("Unable to give any probability: range is 0-100%. Report as 'inconclusive', 'cannot conclude' or 'unknown'", 9)
) 
tbl_col_names <- c("Probability term", "Subjective probability range", "Additional options", "")
ptbl %>% 
  kbl(col.names =tbl_col_names ) %>% 
  kable_paper(full_width = FALSE) %>%
  column_spec(1:3, width = "10em") %>% 
  collapse_rows(columns = 3:4, valign = "top")

```
