project:
  type: website
  output-dir: docs

website:
  title: "EFSA Tutorial on Uncertainty"
  page-footer:
    left: "Copyright 2023, EFSA"
    right:
      - icon: github
        href: https://github.com/dmi3kno/EFSAtutorial
      - icon: twitter
        href: https://twitter.com/EFSA_EU
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Introduction"
        file: introduction.qmd
      - text: "Principles and Methods"
        file: principles-and-methods.qmd
      - text: "Uncertainty Analysis"
        file: uncertainty-analysis.qmd
      - text: "Communication of Uncertainty"
        file: uncertainty-communication.qmd
      - text: "Implementation"
        file: implementation.qmd

  sidebar:
    - title: "Principles and Methods"
      contents:
        - principles-and-methods.qmd
        - section: "Principles of Uncertainty Analysis"
          contents:
          - principles-and-methods/uncertainty-analysis-background.qmd
          - principles-and-methods/uncertainty-analysis-expressions.qmd
          - principles-and-methods/uncertainty-analysis-concerns.qmd
          - principles-and-methods/uncertainty-analysis-key-concepts.qmd
          - principles-and-methods/uncertainty-analysis-main-elements.qmd
          - principles-and-methods/uncertainty-analysis-key-principles.qmd
        - section: "Principles of Uncertainty Communication"
          contents:
          - principles-and-methods/uncertainty-communication-principles.qmd
          - principles-and-methods/uncertainty-communication-communicating.qmd
          - principles-and-methods/uncertainty-communication-audience.qmd
        - section: "Methods for Uncertainty Analysis"
          contents:
          - principles-and-methods/methods.qmd
          - principles-and-methods/methods-qualitative.qmd
          - principles-and-methods/methods-quantitative.qmd
          - principles-and-methods/methods-sources-inputs.qmd
          - principles-and-methods/methods-sources-methodology.qmd
        
    - title: "Uncertainty Analysis"
      contents:
        - uncertainty-analysis.qmd
        - uncertainty-analysis/identifying.qmd
        - uncertainty-analysis/prioritizing.qmd
        - uncertainty-analysis/dividing.qmd
        - uncertainty-analysis/well-defined.qmd
        - uncertainty-analysis/characterising-and-combining.qmd
        - uncertainty-analysis/overall.qmd
        - uncertainty-analysis/future-investigation.qmd
        - uncertainty-analysis/reporting.qmd
    - title: "Communication of Uncertainty"
      contents:
        - uncertainty-communication.qmd
        - section: "Communication Checklists"
          contents:
          - uncertainty-communication/communicator.qmd
          - uncertainty-communication/assessor.qmd
        - section: "Principles of Uncertainty Communication"
          contents:
          - principles-and-methods/uncertainty-communication-principles.qmd
          - principles-and-methods/uncertainty-communication-communicating.qmd
          - principles-and-methods/uncertainty-communication-audience.qmd
        - section: "Expressions of Uncertainty"
          contents:
          - uncertainty-communication/expressions-unqualified.qmd
          - uncertainty-communication/expressions-sources.qmd
          - uncertainty-communication/expressions-direction.qmd
          - uncertainty-communication/expressions-inconclusive.qmd
          - uncertainty-communication/expressions-precise.qmd
          - uncertainty-communication/expressions-approximate.qmd
          - uncertainty-communication/expressions-distribution.qmd
          - uncertainty-communication/expressions-2d.qmd
  search: 
    location: navbar
    type: overlay
execute: 
  freeze: false
  
format:
  html:
    theme: 
      - zephyr
      - special.scss
    mainfont: "Roboto"
    anchor-sections: true
    email-obfuscation: javascript
    toc: true
    link-external-icon: true
    link-external-newwindow: true



