project:
  type: website
  output-dir: docs

website:
  title: "EFSA Tutorial on Uncertainty"
  page-footer:
    left: '"Science, safe food, sustainability"'
    center: "EFSA tutorial on Uncertainty"
    right:
      - text: "Follow us on  "
      - icon: rss
        href: https://www.efsa.europa.eu/en/rss
      - icon: twitter
        href: https://twitter.com/efsa_eu
      - icon: instagram
        href: https://www.instagram.com/one_healthenv_eu/
      - icon: linkedin
        href: https://www.linkedin.com/company/efsa
      - icon: youtube
        href: https://www.youtube.com/user/EFSAchannel
      - icon: spotify
        href: https://open.spotify.com/show/0PZQtMty4NZbgdo0GLIGHm
  navbar:
    background: "#D9D9D9"
    foreground: primary
    title: false
    logo: "img/EFSA_logo.png"
    left:
      - text: "Home"
        file: index.qmd
      #- text: "Introduction"
      #  file: introduction.qmd
      - text: "Principles and Methods"
        file: principles-and-methods.qmd
      - text: "Uncertainty Analysis"
        file: uncertainty-analysis.qmd
      - text: "Communication of Uncertainty"
        file: uncertainty-communication.qmd
      - text: "Implementation"
        file: implementation.qmd

  sidebar:
    - title: "Principles and Methods"
      contents:
        - principles-and-methods.qmd
        - section: "Principles of Uncertainty Analysis"
          contents:
          - principles-and-methods/uncertainty-analysis-background.qmd
          - principles-and-methods/uncertainty-analysis-expressions.qmd
          - principles-and-methods/uncertainty-analysis-concerns.qmd
          - principles-and-methods/uncertainty-analysis-key-concepts.qmd
          - principles-and-methods/uncertainty-analysis-main-elements.qmd
          - principles-and-methods/uncertainty-analysis-key-principles.qmd
        - section: "Principles of Uncertainty Communication"
          contents:
          - principles-and-methods/uncertainty-communication-principles.qmd
          - principles-and-methods/uncertainty-communication-communicating.qmd
        - section: "Methods for Uncertainty Analysis"
          contents:
          - principles-and-methods/methods.qmd
          - principles-and-methods/methods-qualitative.qmd
          - principles-and-methods/methods-quantitative.qmd
          - principles-and-methods/methods-sources-inputs.qmd
          - principles-and-methods/methods-sources-methodology.qmd
        
    - title: "Uncertainty Analysis"
      contents:
        - uncertainty-analysis.qmd
        - uncertainty-analysis/identifying.qmd
        - uncertainty-analysis/prioritizing.qmd
        - uncertainty-analysis/dividing.qmd
        - uncertainty-analysis/well-defined.qmd
        - uncertainty-analysis/characterising-and-combining.qmd
        - uncertainty-analysis/overall.qmd
        - uncertainty-analysis/future-investigation.qmd
        - uncertainty-analysis/reporting.qmd
    - title: "Communication of Uncertainty"
      contents:
        - uncertainty-communication.qmd
        - section: "Communication Checklists"
          contents:
          - uncertainty-communication/communicator.qmd
          - uncertainty-communication/assessor.qmd
        - section: "Principles of Uncertainty Communication"
          contents:
          - principles-and-methods/uncertainty-communication-principles.qmd
          - principles-and-methods/uncertainty-communication-communicating.qmd
        - section: "Expressions of Uncertainty"
          contents:
          - uncertainty-communication/expressions-unqualified.qmd
          - uncertainty-communication/expressions-sources.qmd
          - uncertainty-communication/expressions-direction.qmd
          - uncertainty-communication/expressions-inconclusive.qmd
          - uncertainty-communication/expressions-precise.qmd
          - uncertainty-communication/expressions-approximate.qmd
          - uncertainty-communication/expressions-distribution.qmd
          - uncertainty-communication/expressions-2d.qmd
  search: 
    location: navbar
    type: overlay
execute: 
  freeze: false
  
format:
  html:
    theme: 
      - zephyr
      - special.scss
    mainfont: "Roboto"
    backgroundcolor: "#f9f9f9"
    fontcolor: "#22294D"
    anchor-sections: true
    email-obfuscation: javascript
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    include-before-body: 
      - file: partials/analytics.html



