project:
  type: website
  output-dir: docs

website:
  title: "EFSA Tutorial"
  page-footer:
    left: "Copyright 2023, EFSA"
    right:
      - icon: github
        href: https://github.com/dmi3kno/EFSAtutorial
      - icon: twitter
        href: https://twitter.com/EFSA_EU
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Introduction"
        file: intro.qmd
      - text: "Principles and Methods"
        file: principles.qmd 
      - text: "Uncertainty Analysis"
        file: uncertaintyanalysis.qmd
      - text: "Communication of Uncertainty"
        file: communication.qmd
      - text: "Implementation"
        file: implementation.qmd

  sidebar:
    - title: "Principles and Methods"
      contents:
        - principles.qmd
        - section: "Principles of Uncertainty Analysis"
          contents:
          - pmguidance/pmanalysis_background.qmd
          - pmguidance/pmanalysis_expressions.qmd
          - pmguidance/pmanalysis_keyconcepts.qmd
          - pmguidance/pmanalysis_mainelements.qmd
          - pmguidance/pmanalysis_keyprinciples.qmd
        - section: "Principles of Uncertainty Communication"
          contents:
          - pmguidance/pmcommunication_principles.qmd
          - pmguidance/pmcommunication_communicating.qmd
          - pmguidance/pmcommunication_audience.qmd
        - section: "Methods for Uncertainty Analysis"
          contents:
          - pmguidance/methods.qmd
        
    - title: "Uncertainty Analysis"
      contents:
        - uncertaintyanalysis.qmd
        - uaguidance/identifying.qmd
        - uaguidance/prioritizing.qmd
        - uaguidance/dividing.qmd
        - uaguidance/welldefined.qmd
        - uaguidance/characterizing.qmd
        - uaguidance/combining.qmd
        - uaguidance/overall.qmd
        - uaguidance/futureinvestigation.qmd
        - uaguidance/reporting.qmd
    - title: "Communication of Uncertainty"
      contents:
        - communication.qmd
        - section: "Communication Checklists"
          contents:
          - comguidance/communicator.qmd
          - comguidance/assessor.qmd
        - section: "Principles of Uncertainty Communication"
          contents:
          - pmguidance/pmcommunication_principles.qmd
          - pmguidance/pmcommunication_communicating.qmd
          - pmguidance/pmcommunication_audience.qmd
        - section: "Expressions of Uncertainty"
          contents:
          - comguidance/expressions_unqualified.qmd
          - comguidance/expressions_sources.qmd
          - comguidance/expressions_direction.qmd
          - comguidance/expressions_inconclusive.qmd
          - comguidance/expressions_precise.qmd
          - comguidance/expressions_approximate.qmd
          - comguidance/expressions_distribution.qmd
          - comguidance/expressions_2d.qmd
    - title: "Implementation"
      contents:
        - implementation.qmd
        - implementation/implementationmethods.qmd
        - implementation/implementationexpressions.qmd

execute: 
  freeze: auto

format:
  html:
    theme: 
      - zephyr
      - special.scss
    mainfont: "Roboto"
    anchor-sections: true
    email-obfuscation: javascript
    toc: true



