project:
  type: website
  output-dir: docs

website:
  title: "EFSA Tutorial"
  page-footer:
    left: "Copyright 2023, EFSA"
    right:
      - icon: github
        href: https://github.com/dmi3kno/EFSAtutorial
      - icon: twitter
        href: https://twitter.com/EFSA_EU
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Introduction"
        file: intro.qmd
      - text: "Principles and Methods"
        file: pmguidance/pmanalysis.qmd 
      - text: "Uncertainty Analysis"
        file: uncertaintyanalysis.qmd
      - text: "Communication of Uncertainty"
        file: communication.qmd
      - text: "Implementation"
        file: implementationmethods.qmd

  sidebar:
    - title: "Principles and Methods"
      contents:
        - pmguidance/pmanalysis.qmd
        - pmguidance/pmcommunication.qmd
        - methods.qmd
    - title: "Uncertainty Analysis"
      contents:
        - uncertaintyanalysis.qmd
        - uaguidance/identifying.qmd
        - uaguidance/prioritizing.qmd
        - uaguidance/dividing.qmd
        - uaguidance/welldefined.qmd
        - uaguidance/characterizing.qmd
        - uaguidance/combining.qmd
        - uaguidance/overall.qmd
        - uaguidance/futureinvestigation.qmd
        - uaguidance/reporting.qmd
    - title: "Communication of Uncertainty"
      contents:
        - communication.qmd
        - comguidance/communicator.qmd
        - comguidance/assessor.qmd
    - title: "Implementation"
      contents:
        - implementationmethods.qmd
        - implementationexpressions.qmd

format:
  html:
    theme: 
      - zephyr
      - special.scss
    mainfont: "Roboto"
    anchor-sections: true
    email-obfuscation: javascript
    toc: true



