---
title: "Communication of Uncertainty"
---


**Video transcript**

::: {style="font-size:12px"}

Welcome to the page on Uncertainty Communication! 

The pupose of the section is to introduce you to the "Guidance on Communication of Uncertainty in Scientific Assessments". The material for this page is heavy based on the [Principles of Uncertainty Communication](pmguidance/pmcommunication.qmd) and we strongly recomend that you start your journey into the world of uncertainty communication there.

We divided the material on this page into two sections: there's a section for uncertainty communicators and another one for the assessors. The presentation of the material also varies by the preparation level of the target audience. The material for the Communicators covers the Entry and Informed levels, while the Assessors are encouraged to refer to guidance for communication on the Informed and Technical levels. 

Use one of the buttons below to proceed to the next page, where you will be presented with a communication checklist and the corresponding recommendations addressing the various aspects of uncertainty communication for the different audience levels.


:::

> Introduction to the page. Information about the UC GD and that this is the GD based on the principles from the UC GD and that we recommend looking at those before going through the UC GD page. Instructions on how to explore the page. Recommendations when it can be useful to consult it when you are working with an assessment. 

I am:

```{mermaid}
%%{init:{"theme":"base", "themeVariables": {"primaryColor":"white", "secondaryColor":"white", "tertiaryColor":"white", "mainBkg":"#f2f2f2", "nodeBorder":"#7F7F7F", "clusterBkg":"#FFF9FB"}}}%%
flowchart TB
  A([Communicator])
  B([Assessor])
  click A "comguidance/communicator.html" "Go to Communicator page"
  click B "comguidance/assessor.html" "Go to Assessor page"
```


The introduction section also provides an overview of risk communication in EFSA, covering the main strategies and the criteria for proper audience targeting. We introduce the expressions of uncertainty used at EFSA and invite the user to select one of the two sections to proceed

The rest of the content on the page is split between the communicator, and the assessor role. The user has the opportunity to select the other role and explore the content in the respective section. The Communicator section provides guidance for communication on the entry-level and the informed level, while the Assessor section provides guidance for the technical level.

Finally, both the Communicator and the Assessor roles share the section for the Specific Guidances, consisting of the 9 types of expressions of uncertainty as shown in Figure 4. The content of the Specific Guidances varies depending on the role (the Communicator is shows the entry and informed level and the Assessor is shown the technical level)

Each of the specific guidances (for assessors) is accompanied by a short text and links to best-practice examples (i.e. where these Specific Guidances were followed) in the implementation section (below).

We will also refer to additional information in the Principles and Methods opinion on reporting and communicating uncertainties (Ch 15 and 16).


