---
title: "Introduction"
---

:::: {.panel-tabset}

## Video

<iframe width="560px" height="320px" allowfullscreen="true" allow="autoplay *" title="Sequence_01_Introduction" src="https://lu.instructuremedia.com/embed/f77815e9-1688-4f1c-a44a-7d0924fabcde" frameborder="0"></iframe>

## Text

Welcome to this tutorial on how to identify, characterize and communicate uncertainty in EFSA’s scientific assessments.

Consideration of uncertainty has always been a part of EFSA’s commitment to transparency. According to the EFSA's scientific assessment process, scientists are required to identify and characterise uncertainties and assess their impact on the assessment conclusions. We hope that this tutorial will enhance your understanding of the principles behind the two guidance documents and help you put them into practice.

You will learn how to

 - plan your uncertainty analysis,
 - identify and evaluate sources of uncertainty,
 - describe uncertainties that have not been quantified, and
 - communicate uncertainty to the target audience with confidence.

The tutorial is set up as an interactive website where you can explore and learn by watching, reading, and interacting with the material. You can also find links to selected case studies, opinions and reports which showcase how the principles of uncertainty analysis and communication can be implemented in the assessments!

Look carefully on your screen now. Just above me and across the screen, you see the top menu with the sections named

- Home
- Introduction
- Principles and Methods
- Uncertainty Analysis
- Communication of Uncertainty, and
- Implementation

Right now you are in the **Introduction** section, where you can find me and the text I am reading underneath this video.

**Principles and Methods** menu takes you to the section dedicated to the supporting opinion of the Uncertainty Analysis Guidance and the principles behind the Communication of Uncertainty Guidance. This section describes the rationale behind the two guidances and contains an in-depth discussion of how to handle and communicate uncertainties in scientific assessments. Come back to this section if you are unsure about something or want to learn more about, well, underlying "principles and methods".

The **Uncertainty Analysis** section is dedicated to the first guidance document. It contains general recommendations for the different steps and workflows of an uncertainty analysis for different types of assessments. You can use the flowcharts to plan the uncertainty analysis for your assessment!

The **Communication of Uncertainty** section is dedicated to the second guidance document. It contains checklists for communicators and assessors to ensure quality and transparency in communication with various audiences.

The *Implementation* section contains references to the previously published reports and opinions, applying the principles and methods of uncertainty analysis. We hope that the interactive tables will simplify the search and navigation and highlight some of the work which corresponds well to the concepts you’ve learned from the guidance.

Again, welcome to the tutorial and hope you will find the learning journey fun!
::::


:::{.callout-note}
## Guidance documents

This tutorial refers to the three main guidance documents

- The [Principles and Methods](https://doi.org/10.2903/j.efsa.2018.5122) behind EFSA's Guidance on Uncertainty Analysis in Scientific Assessment
- Guidance on [uncertainty analysis](https://doi.org/10.2903/j.efsa.2018.5123) in scientific assessments
- Guidance on [communication of uncertainty](https://doi.org/10.2903/j.efsa.2019.5520) in scientific assessments
:::

## About

This tutorial is provided within [OC/EFSA/KNOW/2022/01 Lot 2 Trainings on horizontal scientific assessment methodologies EFSA training](https://www.item.fraunhofer.de/en/events/efsa-e-learning-lot2.html).

The tutorial was created by Ullrika Sahlin (ullrika.sahlin [at] cec.lu.se) and Dmytro Perepolkin, CEC, Lund University, Sweden.  


