---
title: "Uncertainty Analysis Guidance"
---

Please chose the process

```{mermaid}
%%{init:{"theme":"base", "themeVariables": {"primaryColor":"white", "secondaryColor":"white", "tertiaryColor":"white", "mainBkg":"#f2f2f2", "nodeBorder":"#7F7F7F", "clusterBkg":"#FFF9FB"}}}%%
flowchart TB
  A([Standardized</br>Assessments])
  B([Case-specific</br>assessments])
  click A "uaguidance/figure1.html" "A standardised assessment follows a pre-established standardised procedure that covers every step of the assessment"
  click B "uaguidance/figure5.html" "Standardised elements (e.g. default values) may be used for some parts of the assessment, but other parts require case-specific approaches"
```


```{mermaid}
%%{init:{"theme":"base", "themeVariables": {"primaryColor":"white", "secondaryColor":"white", "tertiaryColor":"white", "mainBkg":"#f2f2f2", "nodeBorder":"#7F7F7F", "clusterBkg":"#FFF9FB"}}}%%
flowchart TB
  C([Urgent</br>assessments])
  D([Development or revision</br>of guidance documents])
  click C "uaguidance/figure11.html" "Assessments that, for any reason, must be completed within an unusually short period of time or with unusually limited resources, and therefore require streamlined approaches to both assessment and uncertainty analysis"
  click D "uaguidance/figure12.html" "Especially (but not only) those that describe existing standardised procedures or establish new ones"
```


Learn more about

- [Identifying](uaguidance/identifying.qmd) uncertainties affecting the assessment
- [Prioritizing](uaguidance/prioritizing.qmd) uncertainties within the assessment
- [Dividing](uaguidance/dividing.qmd) the uncertainty analysis into parts
- Ensuring that the questions or quantities of interest are [well-defined](uaguidance/welldefined.qmd).
- [Characterizing](characterizing.qmd) uncertainty for parts of the uncertainty analysis
- [Combining](uaguidance/combining.qmd) uncertainty from different parts of the uncertainty analysis
- Characterising [overall](uaguidance/overall.qmd) uncertainty
- Prioritising uncertainties for [future investigation](uaguidance/futureinvestigation.qmd).
- [Reporting](uaguidance/reporting.qmd) uncertainty analysis

