---
title: "Guidance on Communication of Uncertainty"
---

:::: {.panel-tabset}

## Introduction video

<iframe width="560px" height="320px" allowfullscreen="true" allow="autoplay *" title="Sequence_01_UncertaintyCommunication" src="https://lu.instructuremedia.com/embed/80d0207a-7fe7-4f25-bf38-f17c21948716" frameborder="0"></iframe>

## Introduction transcript

Welcome to the page for the EFSA guidance on communication of uncertainty

This page takes you through the suggestions provided for communicators and assessors. 

The guidance consists of a series of questions helping you to tailor the uncertainty communication message targeting the audience at the “entry”, “informed” and “technical” levels.

You can access these checklists by clicking one of the buttons below. 

You can also learn about the principles behind the EFSA guidance on communication of uncertainty. 

Note that the text in this tutorial is a condensed extract from the EFSA guidance on communication of uncertainty. If something is unclear or feels incomplete, or if you want to learn more, we recommend you to consult the original document. Always refer to the guidance documents as your primary source! 

We hope you enjoy the material!

::::

## General guidance 

```{r}
#| label: tbl-ucomm-summary
#| tbl-cap: "General guidance for communicators"
#| echo: false

tibble::tribble(
  ~cat,~txt,
  "Alignment with the assessment", "&bull; Consistency with the degree of certainty &bull; Link uncertainty information to specific event, outcome or quantity &bull;  Any conditions or assumptions related to conclusions",
  "Describing uncertainty with words", "&bull; Do not replace number used to express uncertainty with words &bull; Use exactly the same words to describe the degree of uncertainty (e.g. low, high)",
  "Describing uncertainty with numbers", "&bull; Use % certainty (e.g. 'the experts considered it 90% certain that...') &bull; Positively frame the conclusion as % certainty for more likely outcome &bull; If using both, always communicate numbers first and words second, e.g. '66-90% certain (likely)'",
  "Precautions when using numbers", "&bull; Avoid 'hedging word', such as 'about', 'approximately', and 'up to' &bull; Be clear it's consensus judgment of the experts &bull; Avoid using % of values of interest, e.g. 'The Panel was 90% certain that 3 in 10,000 sheep would be affected by the virus'",
  "Describing sources of uncertainty", "&bull; Provide for informed/technical audience &bull; Make clear all uncertainties have been taken into account in the overall conclusion",
  "Addressing the uncertainties","&bull; Give options for addressing uncertaint (differentiate between RM/RA) &bull; For informed audience differentiate formal requirements for applicants from non-statutory options, e.g. future research"
) |> kableExtra::kbl("html", col.names = NULL, escape = FALSE) |> kableExtra::kable_styling()

```


Use one of the buttons below to proceed to communication checklists!

::: {#start-btn style="font-family: 'Roboto Condensed', Roboto, sans-serif; text-align: center;"}
[I AM A COMMUNICATOR](uncertainty-communication/communicator.qmd){.btn .btn-secondary .btn role="button"}
[I AM AN ASSESSOR](uncertainty-communication/assessor.qmd){.btn .btn-secondary .btn role="button"}
:::

:::{.callout-tip}
## Principles of uncertainty communication


- [Principles of Uncertainty Communication](principles-and-methods/uncertainty-communication-principles.qmd).
- [Communicating Scientific Uncertainties](principles-and-methods/uncertainty-communication-principles.qmd), covering risk communication mandate, risk perception and the uncertainty communicaiton challenges.
:::

The Uncertainty Analysis GD contains several options for carrying out an uncertainty analysis. The Communication of Uncertainty GD provides recommendations for communicating the types of expressions of uncertainty that are normally produced when uncertainty analysis is conducted by following those options. It does not include expressions that are discouraged by the
Uncertainty Analysis GD, or other expressions that may be generated by some more specialised methods and the outputs of some methods for sensitivity analysis.

It is currently expected that, in many assessments, the conclusion, summary and abstract of the assessment will not contain expressions of uncertainty. This may arise in two types of situation, as indicated in the description for ‘unqualified conclusions’. 


:::{.callout-tip}
## Expressions of uncertainty

- [Unqualified conclusion](uncertainty-communication/expressions-unqualified.qmd), with no expression of uncertainty
- Description of [sources of uncertainty](uncertainty-communication/expressions-sources.qmd) 
- Qualitative description of the [direction and/or magnitude](uncertainty-communication/expressions-direction.qmd) of uncertainty using words or symbols
- [Inconclusive assessment](uncertainty-communication/expressions-inconclusive.qmd)
- A [precise probability](uncertainty-communication/expressions-precise.qmd)
- An [approximate probability](uncertainty-communication/expressions-approximate.qmd)
- A [probability distribution](uncertainty-communication/expressions-distribution.qmd)
- A [two-dimensional probability](uncertainty-communication/expressions-2d.qmd) distribution
:::

</br>
</br>

::: {#start-btn style="font-family: 'Roboto Condensed', Roboto, sans-serif; text-align: center;"}
[Return to Home page](index.qmd){.btn .btn-secondary .btn role="button"}
:::