---
title: "Reporting uncertainty analysis"
---

::: {.callout-tip collapse="true" appearance="minimal"}
## Requirements on reporting

Uncertainty analysis is part of scientific assessment; so in all cases, it should be reported in a manner consistent with EFSA’s general principles regarding transparency and reporting. In particular, it is important to list the sources of uncertainty that have been identified and document how they were identified, how each source of uncertainty has been evaluated and how they have been combined, where and how data and expert judgement have been used, what methodological approaches have been used (including models of any type) and the rationale for choosing them, and what the results were. Where the assessment used methods that are already described in other documents, it is sufficient to refer to those.

The uncertainty analysis should be reported in all assessments with two exceptions: 

For standard assessments where no case-specific sources of uncertainty have been identified, the EFSA output must at minimum state what standardised procedure was followed and report that non-standard uncertainties were checked for and none were found. 

If non-standard uncertainties are found, the assessors should report that standard uncertainties in the assessment are accepted to be covered by the standardised procedure and the uncertainty analysis is therefore restricted to non-standard uncertainties that are particular to this assessment, the analysis of which should then be reported as described below. 

The level of detail can be reduced due to time constraints in urgent assessments. 

:::

::: {.callout-tip collapse="true" appearance="minimal"}
## Where to report the uncertainty analysis

The location of information on the uncertainty analysis within the assessment report should be chosen to maximise transparency and accessibility for readers. This may be facilitated by including one or more separate sections on uncertainty analysis, which are identifiable in the table of contents. 

:::


::: {.callout-tip collapse="true" appearance="minimal"}
## How to report the uncertainty analysis

The Scientific Committee has stated that EFSA’s scientific assessments must report clearly and unambiguously what sources of uncertainty have been identified and characterise their overall impact on the assessment conclusion, in a form compatible with the requirements of decision-makers and any legislation applicable to the assessment in hand. See Ch 15 in the Uncertainty Analysis Guidance for examples. 

In other cases, where the form for reporting conclusions is not specified by decision-makers or legislation, the assessment conclusion should include (a) a clear statement of the overall result for those uncertainties that have been quantified and (b) a clear description of unquantified sources of uncertainty, i.e. those that could not be included in the quantitative analysis. 

The former will generally express the overall quantified uncertainty about the assessment conclusion using probabilities, probability distributions, probability bounds, or ranges from the [approximate probability scale](../principles-and-methods/uncertainty-communication-principles.qmd#tbl-approx-probscale). 

For each unquantified source of uncertainty, the assessors should describe (either in the conclusion or another section, as appropriate) which part(s) of the assessment it arises in, the cause or reason for it, how it affects the assessment (but not how much), why it is difficult to quantify, what assumptions have been made about it in the assessment and what could be done to reduce or better characterise it. 

Assessors must avoid using any words that imply a judgement about the magnitude or likelihood of the unquantified sources of uncertainty. 

:::


::: {.callout-tip collapse="true" appearance="minimal"}
## Prepare reporting for the summary section

 In addition to the detailed reporting of the methods and results of the uncertainty analysis, the assessors should prepare a concise summary of the overall characterisation of uncertainty in format and style suitable for inclusion in the executive summary of the assessment report. This should present, in the simplest terms possible, a quantitative expression of the combined effect on the assessment conclusion of those uncertainties that have been quantified, and a brief description of any unquantified sources of uncertainty. 

:::

::: {.callout-tip collapse="true" appearance="minimal"}
##  Be consistent

Assessors must check that there is no incompatibility between the reporting of the uncertainty analysis and the assessment conclusions. 

:::

