---
title: "Precise probability"
---

## What is a probability

A single number (in EFSA outputs: a percentage between 0% and 100%) quantifying the likelihood of either: 

- A specified answer to a question (e.g. a 'yes' answer to a 'yes/no' question) 
- A specified quantity lying in a specified range of values, or above or below a specified value (e.g. 90% probability that between 10 and 100 infected organisms will enter the EU in 2019; 5% probability that more than 100 infected organisms will enter).

:::{.callout-note}
## Note

The term 'precise' is used here to refer to how the probability is expressed, as a single number, and does not imply that it is actually known with absolute precision, which is not possible.
:::

## Frequentist vs Bayesian view

There are two major perspectives on the scope of probability as a measure for quantifying uncertainty. 

The first perspective, known as the **frequentist view**, argues that probability should be limited to addressing uncertainties caused by variability and should not be extended to uncertainties arising from limitations in knowledge. In other words, frequentists do not consider probability as a relevant concept for measuring uncertainty associated with imperfect knowledge. Consequently, this viewpoint does not offer a solution for characterizing the many other types of uncertainty, such as data quality and extrapolation, which are frequently significant in EFSA assessments.

The second perspective, known as the **subjectivist (Bayesian) view**, asserts that probability serves as a direct personal expression of uncertainty. According to this view, any well-defined question or quantity can have its uncertainty quantified using probability. Therefore, it can encompass uncertainties caused by limitations in knowledge, as well as those caused by variability.

### Advantages of subjective probability

Subjective probability enhances comparability among individuals when expressing uncertainties. It allows for intuitive comparisons based on shared understanding, such as coin tosses or dice rolls. An operational definition enables subjective probabilities for well-defined quantities or categorical questions. It also permits the legitimate application of mathematical tools to subjective probabilities, facilitating judgments on combining sources of uncertainty. The Guidance encourages the use of subjective probability to express uncertainty, except when quantification is particularly challenging (see Section 5.12 of the [SO](https://doi.org/10.2903/j.efsa.2018.5122)).


### Combining uncertainties

The subjectivist interpretation of probability does not exclude the frequentist interpretation, but it requires reinterpreting frequentist probabilities as subjective probabilities to combine them with other sources of uncertainty. This is particularly relevant when integrating probabilities from statistical data analysis with probabilities derived from expert judgment. Bayesian analysis already yields subjective probabilities, but confidence intervals from frequentist analysis would need reinterpretation. The process and appropriateness of such reinterpretation are discussed in Section 11.2.1, considering that probabilities from statistical analysis may still entail additional uncertainties requiring expert judgment.

## Approximate probability

Probabilities need not be expressed precisely, and in practice, they are always approximate to some extent. Assessors typically provide approximate probabilities within a specified range instead of specifying them to infinite decimal places. Learn more about [approximate probabilities](expressions-approximate.qmd) in the respective section of the tutorial.


