---
title: "Communication of Uncertainty for Assessors"
---

Template for identifying messages with associated uncertainty expressions, and specific guidance for their communication:

<!-- ######################## Section 1 ###################### -->
::: {.callout-tip collapse="true" appearance="minimal"}
# 1. Did the scientific assessment for this message identify any non-standard uncertainties? 

:::: {.panel-tabset}

## Yes

If an **unqualified conclusion is required**, follow the guidance for unqualified conclusions (see Question 5 here). If an **unqualified conclusion is not required**, state the result of the standardised procedure in the form expressed by the assessors. Also communicate the uncertainty expressions for this message, consulting the respective guidance boxes.

## No

Report the conclusion as expressed by assessors and state that a standardised assessment procedure was followed that takes account of standard uncertainties, and no non-standard uncertainties were identified.

::::
:::

<!-- ######################## Section 2 ###################### -->
:::{.callout-tip collapse="true" appearance="minimal"}

# 2. Does the scientific output list or describe the sources or causes of any uncertainties affecting this message? 

:::: {.panel-tabset}

## Informed

- State that uncertainties exist, using the wording in the scientific output. 
- Include in the message a brief description of the sources of uncertainty that have the biggest impact on the respective key messages. (If necessary, consult the assessors to identify these.)

> **Example:**
> *"The experts identified limitations in the data on exposure and toxic effects of ZEN and its modified forms, for example (...)"* [Based on EFSA 2017;15(7):4851](https://doi.org/10.2903/j.efsa.2017.4851)

## Technical

- When documenting sources of uncertainty in the assessment report, assessors should include brief text descriptions suitable for subsequent use in communications to informed audiences without using specialist technical terms. - Assessors should try to identify which sources of uncertainty have most influence on their conclusions, either by qualitative assessment or by influence or sensitivity analysis [UA](https://doi. org/10.2903/j.efsa.2018.5123).
- Where there is conflicting evidence on an issue, this is a source of uncertainty which must be documented and taken into account in uncertainty analysis, and may be assessed using a weight of evidence approach [WE](https://doi.org/10.2903/j.efsa.2017.4971).

::::
:::


<!-- ######################## Section 3 ###################### -->
:::{.callout-tip collapse="true" appearance="minimal"}

# 3. Is the direction and/or degree of uncertainty expressed verbally (i.e. with terms like 'low', 'medium', 'high') or with symbols (e.g. '+' or '-')? 

:::: {.panel-tabset}

## Informed

- Avoid altering the wordings used by assessors to describe the direction and/or degree of uncertainty, or factors contributing to uncertainty (Box 2). Always check the rewording with the assessors if you do. 
- State clearly what outcomes and conditions this expression of uncertainty refers to. 
- Make clear that any uncertainty referred to in the communication has been taken into account in the assessment conclusion.
- Before communicating the uncertainty expression, describe a few examples of the evidence/data that were considered and the uncertainties affecting the assessment.  
- Optionally, mention specific methods that were used in evaluating the uncertainty.  
- Optionally, mention factors contributing to the overall uncertainty, including the relative importance of individual sources of uncertainty and things like the relevance and reliability of evidence (e.g. in weight of evidence assessments, [see WE](https://doi.org/10.2903/j.efsa.2017.4971)).  
- Clearly distinguish individual sources of uncertainty from overall uncertainty about the assessment conclusions.  

> **Example:**
> *"The Panel noted that a high proportion of measurements of ZEN and its modified forms in feed were below the limit of detection, leading to very high uncertainty when estimating exposure"* [Based on EFSA 2017;15(7):4851](https://doi.org/10.2903/j.efsa.2017.4851)

## Technical

- If using "+" and "−" or other symbols to indicate the direction and magnitude of uncertainty, accompany these with quantitative definitions of their meaning, [as discussed in Annex 5 of PM](https://doi.org/10.2903/j.efsa.2018.5122).

::::
:::


<!-- ######################## Section 4 ###################### -->
:::{.callout-tip collapse="true" appearance="minimal"}

# 4. Does this message report an inconclusive assessment outcome? 

:::: {.panel-tabset}

## Informed

- Describe the main sources of uncertainty in more detail, but concisely, following the guidance in Box 2. - Inconclusive assessments are especially likely to include options or requirements for obtaining further data. Communicate these as instructed in Section 3.1.5 on ‘Addressing the uncertainties’.

## Technical

- When explaining why the assessment is inconclusive, include a description of the key sources of uncertainty that are responsible for this.   
- If the assessment is not totally uncertain, try to express what the science can say and quantify the uncertainty unless the risk manager/legislation requires that only unqualified conclusions be given.

::::
:::

<!-- ######################## Section 5 ###################### -->
:::{.callout-tip collapse="true" appearance="minimal"}

# 5. Do risk managers expect or does legislation require that this message should be expressed as an unqualified conclusion, without any expression of uncertainty? 

:::: {.panel-tabset}

## Informed

- As for the entry level. 
- Optionally, describe briefly how the assessment was made (i.e. what evidence and methods were used to arrive at the conclusions). 
- Briefly describe some examples of uncertainties affecting the assessment for this message, as identified in your completed template, consulting Box 4 for guidance on how to communicate this. 
- If the assessment contains any verbal or numerical expression of the impact of the uncertainties as identified in your template, follow the respective guidance in Boxes 6–9 below. 
- Say that the assessors took the uncertainties into account when reaching their conclusion(s) for this message.

## Technical

- Provide the information needed for the FAQ required at the entry level communications (see above). 
- Specify what level of certainty is associated with each unqualified conclusion. Risk managers can explain why that level of certainty is appropriate for decisionmaking, if considered necessary. Make this information available to interested parties in suitable ways, e.g. in an FAQ and/or in documentation or guidance on the assessment methodology.
- State clearly what the probability refers to, including whether it refers to a numerical estimate or a qualitative conclusion. When the probability refers to a numerical estimate, also state the range of the quantity that the probability refers to (see example below).


::::
:::


<!-- ######################## Section 6 ###################### -->
:::{.callout-tip collapse="true" appearance="minimal"}

# 6. Is the uncertainty described with numbers as a precise probability? 

:::: {.panel-tabset}

## Informed

- State clearly what the probability refers to, including whether it refers to a numerical estimate or a qualitative conclusion. When the probability refers to a numerical estimate, also state the range of the quantity that the probability refers to (see example below).
- Before giving the probability, describe a few examples of the evidence/data that were considered and the uncertainties affecting the assessment, and state that the experts took these into account when assessing their level of certainty. 
- Optionally, mention specific methods that were used in quantifying the uncertainty, e.g. modelling, statistical analysis, expert knowledge elicitation (EKE), or a combination of these.


## Technical

- No specific guidance for assessors other than the general guidance for assessors in Section 3.2 (above).

::::
:::


<!-- ######################## Section 7 ###################### -->
:::{.callout-tip collapse="true" appearance="minimal"}

# 7. Is the uncertainty described with numbers as an approximate probability? 

:::: {.panel-tabset}

## Informed

- State clearly what the probability refers to, including whether it refers to a numerical estimate or a qualitative conclusion. When the probability refers to a numerical estimate, also state the range of the quantity that the probability refers to. - An approximate probability may comprise a range of probabilities chosen by the assessors from the approximate probability scale (Table 4), or a different range of probabilities specified by the assessors. 
- Always communicate the quantitative range of probabilities because this expresses the assessors’ conclusion without ambiguity. If a verbal expression is also used, present the quantitative probability first (e.g. ‘66–90% certain (likely)’) because it has been shown that this order leads to more consistent understanding than if the verbal expression is presented first (see Section 3.1) • To avoid inconsistency and misunderstanding, do not use the verbal terms in Table 4 to refer to any probabilities or ranges of probabilities other than those shown in this table.
- Before giving the probability, describe a few examples of the evidence/data that were considered and the uncertainties affecting the assessment, and state that the experts took these into account when assessing their level of certainty. 
- Optionally, mention specific methods that were used in quantifying the uncertainty, e.g. modelling, statistical analysis, expert knowledge elicitation (EKE), or a combination of these.

## Technical

- Use different probabilities or ranges from those shown in Table 4 if they better express your judgement (EFSA Scientific Committee et al., 2018a). In such cases, avoid accompanying it with any verbal probability expression because a harmonised interpretation exists only for the terms in Table 4.
::::
:::


<!-- ######################## Section 8 ###################### -->
:::{.callout-tip collapse="true" appearance="minimal"}

# 8. Is the uncertainty described with numbers as a one-dimensional probability distribution? 

:::: {.panel-tabset}

## Informed

Informed level

## Technical

Technical level

::::
:::


<!-- ######################## Section 9 ###################### -->
:::{.callout-tip collapse="true" appearance="minimal"}

# 9. Is the uncertainty described with numbers as a two-dimensional probability distribution?

:::: {.panel-tabset}

## Informed

Informed level

## Technical

Technical level

::::
:::





